name: SpleefPE
main: sp\Main
api: 3.0.0
version: 1.0.1
author: ipad54 and ruslantopchik
website: https://github.com/ipad54/SpleefPE
commands:
  spleef:
    description: spleef
    permission: spleef.cmd.use
    default: op
